/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../src/components/top/auth.vue')['default']
    Back: typeof import('./../src/components/top/back.vue')['default']
    Bars: typeof import('./../src/components/playBar/bars.vue')['default']
    copy: typeof import('./../src/components/playBar/playBar copy.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LeftMenu: typeof import('./../src/components/LeftMenu.vue')['default']
    Lines: typeof import('./../src/components/common/lines.vue')['default']
    List: typeof import('./../src/components/list/list.vue')['default']
    Loading: typeof import('./../src/components/loading.vue')['default']
    Logo: typeof import('./../src/components/top/logo.vue')['default']
    MSearch: typeof import('./../src/components/top/search/mSearch.vue')['default']
    PlayBar: typeof import('./../src/components/playBar/playBar.vue')['default']
    'PlayBar copy': typeof import('./../src/components/playBar/playBar copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunHouse: typeof import('./../src/components/playBar/runHouse.vue')['default']
    SongList: typeof import('./../src/components/songList.vue')['default']
    SongNameMobile: typeof import('./../src/components/playBar/songNameMobile.vue')['default']
    TimeText: typeof import('./../src/components/playBar/timeText.vue')['default']
    Top: typeof import('./../src/components/top/index.vue')['default']
  }
}
