/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../src/components/top/auth.vue')['default']
    Back: typeof import('./../src/components/top/back.vue')['default']
    Bars: typeof import('./../src/components/playBar/bars.vue')['default']
    Buttons: typeof import('./../src/components/common/buttons.vue')['default']
    Comment: typeof import('./../src/components/common/comment.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LeftMenu: typeof import('./../src/components/Menu/LeftMenu.vue')['default']
    Lines: typeof import('./../src/components/common/lines.vue')['default']
    List: typeof import('./../src/components/list/list.vue')['default']
    Loading: typeof import('./../src/components/Loading/loading.vue')['default']
    Login: typeof import('./../src/components/Auth/login.vue')['default']
    Logo: typeof import('./../src/components/top/logo.vue')['default']
    LyricView: typeof import('./../src/components/common/lyricView.vue')['default']
    MSearch: typeof import('./../src/components/top/search/mSearch.vue')['default']
    PlayBar: typeof import('./../src/components/playBar/playBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunHouse: typeof import('./../src/components/playBar/runHouse.vue')['default']
    SettingBtn: typeof import('./../src/components/common/SettingBtn.vue')['default']
    SongListHeader: typeof import('./../src/components/common/songListHeader.vue')['default']
    SongListMenu: typeof import('./../src/components/Menu/songListMenu.vue')['default']
    SongListView: typeof import('./../src/components/list/songListView.vue')['default']
    SongNameMobile: typeof import('./../src/components/playBar/songNameMobile.vue')['default']
    Tag: typeof import('./../src/components/common/tag.vue')['default']
    TimeText: typeof import('./../src/components/playBar/timeText.vue')['default']
    Top: typeof import('./../src/components/top/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
