/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../src/components/top/auth.vue')['default']
    Back: typeof import('./../src/components/top/back.vue')['default']
    Bars: typeof import('./../src/components/playBar/bars.vue')['default']
    Buttons: typeof import('./../src/components/common/buttons.vue')['default']
    CloudList: typeof import('./../src/components/list/cloudList.vue')['default']
    copy: typeof import('./../src/components/list/list copy.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LeftMenu: typeof import('./../src/components/Menu/LeftMenu.vue')['default']
    Lines: typeof import('./../src/components/common/lines.vue')['default']
    List: typeof import('./../src/components/list/list.vue')['default']
    Loading: typeof import('./../src/components/Loading/loading.vue')['default']
    Login: typeof import('./../src/components/Auth/login.vue')['default']
    Logo: typeof import('./../src/components/top/logo.vue')['default']
    MSearch: typeof import('./../src/components/top/search/mSearch.vue')['default']
    PlayBar: typeof import('./../src/components/playBar/playBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunHouse: typeof import('./../src/components/playBar/runHouse.vue')['default']
    SongListHeader: typeof import('./../src/components/common/songListHeader.vue')['default']
    SongListMenu: typeof import('./../src/components/Menu/songListMenu.vue')['default']
    SongListView: typeof import('./../src/components/list/songListView.vue')['default']
    SongNameMobile: typeof import('./../src/components/playBar/songNameMobile.vue')['default']
    TimeText: typeof import('./../src/components/playBar/timeText.vue')['default']
    Top: typeof import('./../src/components/top/index.vue')['default']
  }
}
